### PR TITLE
fix for the issue https://github.com/aws-samples/aws-keyspaces-lambda…

### PR DESCRIPTION
**Pull request by deepaksinghcs14**
…-python/issues/1

*Issue #, https://github.com/aws-samples/aws-keyspaces-lambda-python/issues/1

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by deepaksinghcs14** [comment]
@triha74 please review, I have tested it and it's working fine

**Comment by triha74** [comment]
Thanks for helping fix.

I think that instead of having hard coded placeholders in the deploy script its better to do 

```
AWS_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
npx cdk bootstrap aws://${AWS_ACCOUNT}/${AWS_DEFAULT_REGION}
```

Alos might as well use the latest v1 cdk 1.104.0

**Comment by deepaksinghcs14** [comment]
@triha74 thanx for the feedback, I have fixed that.

**Comment by triha74** [comment]
Thanks

Merged it

**Pull request merged**
